// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCCfVQqiWimPztfZ4TXijz4zHEx44BFCk',
    appId: '1:541774402902:web:2e3242b7722bbfc08672f7',
    messagingSenderId: '541774402902',
    projectId: 'hummingbird-express',
    authDomain: 'hummingbird-express.firebaseapp.com',
    storageBucket: 'hummingbird-express.firebasestorage.app',
    measurementId: 'G-P429PGLXHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUSZyLvrfJXEKTPkouWlm9NFfK6e0Ly4g',
    appId: '1:541774402902:android:45a5520154be80da8672f7',
    messagingSenderId: '541774402902',
    projectId: 'hummingbird-express',
    storageBucket: 'hummingbird-express.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUQhuXUJUoIaKjPZ0TLchECzNed7IAX0o',
    appId: '1:541774402902:ios:1a88e3ec7e3825088672f7',
    messagingSenderId: '541774402902',
    projectId: 'hummingbird-express',
    storageBucket: 'hummingbird-express.firebasestorage.app',
    iosBundleId: 'com.example.hummingbirdExpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUQhuXUJUoIaKjPZ0TLchECzNed7IAX0o',
    appId: '1:541774402902:ios:1a88e3ec7e3825088672f7',
    messagingSenderId: '541774402902',
    projectId: 'hummingbird-express',
    storageBucket: 'hummingbird-express.firebasestorage.app',
    iosBundleId: 'com.example.hummingbirdExpress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCCfVQqiWimPztfZ4TXijz4zHEx44BFCk',
    appId: '1:541774402902:web:c2fa20d6d6bdcb318672f7',
    messagingSenderId: '541774402902',
    projectId: 'hummingbird-express',
    authDomain: 'hummingbird-express.firebaseapp.com',
    storageBucket: 'hummingbird-express.firebasestorage.app',
    measurementId: 'G-WS8JGSN1RT',
  );
}
